// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtHBLG8NAUPPMzdGatBGEnTssznrSmFw',
    appId: '1:569453642351:web:8a19752d827d0d2e55039a',
    messagingSenderId: '569453642351',
    projectId: 'school-9845c',
    authDomain: 'school-9845c.firebaseapp.com',
    databaseURL: 'https://school-9845c-default-rtdb.firebaseio.com',
    storageBucket: 'school-9845c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1M8hYYuMbsitAs8pEmo26wdI_lJ0Cu9w',
    appId: '1:569453642351:android:32d5c2847f176f2555039a',
    messagingSenderId: '569453642351',
    projectId: 'school-9845c',
    storageBucket: 'school-9845c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhEUKPyQLLRFbb3MQUSSDn5cvBoV2A-yo',
    appId: '1:569453642351:ios:6b56beb21c4fbff155039a',
    messagingSenderId: '569453642351',
    projectId: 'school-9845c',
    storageBucket: 'school-9845c.appspot.com',
    iosBundleId: 'com.example.flutterSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhEUKPyQLLRFbb3MQUSSDn5cvBoV2A-yo',
    appId: '1:569453642351:ios:da6cbf0b803e73a055039a',
    messagingSenderId: '569453642351',
    projectId: 'school-9845c',
    storageBucket: 'school-9845c.appspot.com',
    iosBundleId: 'com.example.flutterSchool.RunnerTests',
  );
}
